config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  scope module: 'v1' do
    resources :users, only: [:show]
    resources :trips, only: [:create, :destroy]
    resources :pickups, only: [:create, :destroy]
  end

  root to: 'v1/users#show'

  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/ridable.rb
module Ridable
  extend ActiveSupport::Concern

  def departure_time_cannot_be_in_the_past
    unless departure_time >= 5.minutes.ago
      errors[:departure_time] << "Departure Time cannot be in the past"
      return false
    end
  end
end

app/models/pickup.rb
class Pickup < ApplicationRecord
  include Ridable

  validates :passenger, presence: true
  validates :departure_time, presence: true
  validate :user_is_a_passenger, if: :passenger
  validate :departure_time_cannot_be_in_the_past, if: :departure_time

  belongs_to :source, class_name: "Place"
  belongs_to :destination, class_name: "Place"
  belongs_to :passenger, class_name: "User"

  private

  def user_is_a_passenger
    unless passenger.role == "passenger"
      errors[:passenger] << "User is not a passenger"
      return false
    end
  end
end

app/models/place.rb
class Place < ApplicationRecord
  validates_uniqueness_of(:name)
  validates :longitude, uniqueness: { scope: :latitude }

  has_many :source_trips, class_name: "Trip", foreign_key: "source_id"
  has_many :destination_trips, class_name: "Trip", foreign_key: "destination_id"

  has_many :source_pickups, class_name: "Pickup", foreign_key: "source_id"
  has_many :destination_pickups, class_name: "Pickup", foreign_key: "destination_id"

end

app/models/trip.rb
class Trip < ApplicationRecord
  include Ridable

  belongs_to :source, class_name: "Place"
  belongs_to :destination, class_name: "Place"
  belongs_to :driver, class_name: "User"

  validates :driver, presence: true
  validates :departure_time, presence: true
  validates :number_seats, presence: true
  validate :departure_time_cannot_be_in_the_past, if: :departure_time
  validate :user_is_a_driver, if: :driver

  private

  def user_is_a_driver
    unless driver.role == "driver"
      errors[:driver_id] << "User is not a driver"
      return false
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  enum role: [:driver, :passenger]
  
  validates_presence_of :phone_number, :role
  validates :phone_number, uniqueness: true
  validates_length_of :name, minimum: 6


  has_many :trips, foreign_key: "driver_id", dependent: :destroy
  has_many :pickups, foreign_key: "passenger_id", dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!
  
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:role, :phone_number, :name])
  end
end

app/controllers/v1/pickups_controller.rb
module V1
  class PickupsController < ApplicationController
    def create
      @pickup = Pickup.new(pickup_params)
      if @pickup.save
        flash[:success] = "Pickup created!"
      else
        flash[:danger] = "Failed to create pickup"
      end
      redirect_to root_path
    end

    def destroy
      @pickup = Pickup.find_by(id: params[:id])
      if @pickup.nil?
        flash[:notice] = "Pickup already deleted"
      else
        @pickup.destroy
        flash[:success] = "Pickup deleted"
      end
      redirect_to root_path
    end

    private

    def pickup_params
      params.require(:pickup).permit(
        :departure_time,
        :destination_id,
        :source_id
        ).merge(passenger_id: current_user.id)
    end
  end
end

app/controllers/v1/trips_controller.rb
module V1
  class TripsController < ApplicationController
    def create
      @trip = Trip.new(trip_params)
      if @trip.save
        flash[:success] = "Trip created!"
      else
        flash[:danger] = "Failed to create trip"
      end
      redirect_to root_path
      # @trip = Trip.create!(trip_params)
    end

    def destroy
      @trip = Trip.find_by(id: params[:id])
      if @trip.nil?
        flash[:notice] = "Trip already deleted"
      else
        @trip.destroy
        flash[:success] = "Trip deleted"
      end
      redirect_to root_path
    end

    private

    def trip_params
      params.require(:trip).permit(
        :departure_time,
        :number_seats,
        :destination_id,
        :source_id
        ).merge(driver_id: current_user.id)
    end
  end
end

app/controllers/v1/users_controller.rb
module V1
  class UsersController < ApplicationController
    before_action :authenticate_user!, only: [:show]

    def show
      redirect_to new_user_session_path unless user_signed_in?
      if current_user.role == "driver"
        @trip = Trip.new
      else
        @pickup = Pickup.new
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pickups_helper.rb
module PickupsHelper
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse header">
  <div class="container">
    <%= link_to "Raye7", root_path, class: "btn" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <ul>
            <li> <%= current_user.name %>
            <li> <%= link_to "Logout", destroy_user_session_path, method: :delete, class: 'btn' %> </li>
          </ul>
        <% else %>
          <ul>
            <li><%= link_to "Log in", new_user_session_path, class: "btn" %></li>
            <li><%= link_to "Sign up", new_user_registration_path, class: "btn" %> </li>
          </ul>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Raye7Prototype</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%=message_type%>"><%= message %></div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <div id = "error_explanation" >
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>
    </div>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li> <%= msg %> </li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_ride.html.erb
<%= form_for object, url: url do |f| %>

  <%= f.label(:departure_time) %><br>
  <%= f.datetime_select(:departure_time) %><br>

  <%= f.label(:source_id) %><br>
  <%= f.number_field(:source_id) %><br>

  <%= f.label(:destination_id) %><br>
  <%= f.number_field(:destination_id) %><br>

  <% if current_user.role == "driver" %>
    <%= f.label(:number_seats) %> <br>
    <%= f.number_field(:number_seats) %> <br>
  <% end %>

  <%= f.submit "Create" %>
<% end %>

app/views/users/show.html.erb
<% if current_user.role == "driver" %>
  <%= render 'shared/ride', object: @trip, url: trips_path %>  
  <%= render current_user.trips %>
<% else %>
  <%= render 'shared/ride', object: @pickup, url: pickups_path %>
  <%= render current_user.pickups %>
<% end %>

app/views/v1/pickups/_pickup.html.erb
<%= pickup.source.name %> -> <%= pickup.destination.name %> at <%= pickup.departure_time %>
| <%= link_to "delete", pickup_path(pickup.id) , method: :delete, data: { confirm: "You sure?" } %><br>

app/views/v1/trips/_trip.html.erb
<%= trip.source.name %> -> <%= trip.destination.name %> at <%= trip.departure_time %>
| <%= link_to "delete", trip_path(trip.id) , method: :delete, data: { confirm: "You sure?" } %><br>

app/views/v1/users/show.html.erb
<% if current_user.role == "driver" %>
  <%= render 'shared/ride', object: @trip, url: trips_path %>  
  <%= render current_user.trips.includes(:source, :destination) %>
<% else %>
  <%= render 'shared/ride', object: @pickup, url: pickups_path %>
  <%= render current_user.pickups.includes(:source, :destination) %>
<% end %>